import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { FunctionDoc, Overview, TechStack } from '../../src/types';

const firebaseMocks = vi.hoisted(() => ({
  getDoc: vi.fn(),
  setDoc: vi.fn(),
}));

const openrouterMocks = vi.hoisted(() => ({
  callOpenRouterStructured: vi.fn(),
  formatOpenRouterFailure: vi.fn(),
  isOpenRouterFailure: vi.fn(),
}));

vi.mock('../../src/lib/firebase', () => firebaseMocks);
vi.mock('../../src/config', () => ({
  config: {
    openrouter: {
      apiKey: 'test-key',
      model: 'deepseek/test-model',
      fallbackModels: [],
      maxTokens: 4096,
      retryCount: 0,
      timeoutMs: 1000,
      strictJsonSchema: true,
      appName: 'DevHub',
      siteUrl: '',
    },
  },
}));
vi.mock('../../src/lib/logger', () => ({
  createLogger: () => ({ debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() }),
}));
vi.mock('../../src/ai/openrouter', () => openrouterMocks);

import { extractAll } from '../../src/ai/extraction';

const techStack: TechStack = {
  language: 'TypeScript',
  framework: 'Express',
  runtime: 'Node.js',
  buildTool: 'TypeScript compiler',
  testingFramework: 'Vitest',
  database: 'Firebase',
  otherTools: ['Zod'],
};

const overview: Overview = {
  oneLiner: 'AI generated one liner.',
  summary: 'AI generated summary.',
  purpose: 'AI generated purpose.',
  targetUsers: 'Backend developers',
};

const aiFunction: FunctionDoc = {
  name: 'hello',
  type: 'function',
  file: 'src/index.ts',
  line: 1,
  signature: 'export function hello(name: string)',
  description: 'AI generated function description with useful details.',
  params: [{ name: 'name', type: 'string', description: 'Name to greet' }],
  returns: { type: 'string', description: 'Greeting text' },
  throws: [],
  dependencies: [],
};

const files = [
  {
    path: 'package.json',
    content: JSON.stringify({
      name: 'demo-api',
      description: 'Small API',
      scripts: { dev: 'tsx src/index.ts' },
      dependencies: { express: '^4.22.1' },
      devDependencies: { typescript: '^5.9.3', vitest: '^4.1.5' },
    }),
  },
  {
    path: 'src/index.ts',
    content: [
      'export function hello(name: string) { return `Hello ${name}`; }',
      'export class Greeter {}',
    ].join('\n'),
  },
  { path: 'README.md', content: '# Demo API\n\nSmall API.' },
];

describe('extractAll with AI enabled', () => {
  beforeEach(() => {
    firebaseMocks.getDoc.mockReset();
    firebaseMocks.setDoc.mockReset();
    openrouterMocks.callOpenRouterStructured.mockReset();
    openrouterMocks.formatOpenRouterFailure.mockReset();
    openrouterMocks.isOpenRouterFailure.mockReset();
    firebaseMocks.getDoc.mockResolvedValue({ repoId: 'repo-1' });
    openrouterMocks.isOpenRouterFailure.mockReturnValue(true);
    openrouterMocks.formatOpenRouterFailure.mockReturnValue('OpenRouter temporarily unavailable.');
  });

  it('uses AI responses and persists model metadata when every AI step succeeds', async () => {
    openrouterMocks.callOpenRouterStructured
      .mockResolvedValueOnce(techStack)
      .mockResolvedValueOnce(overview)
      .mockResolvedValueOnce([aiFunction])
      .mockResolvedValueOnce({ markdown: '# AI README\n\nGenerated by AI.' });

    const result = await extractAll('repo-1', 'demo-api', 'package.json\nsrc/index.ts\nREADME.md', files, {
      sourceHash: 'hash-1',
    });

    expect(result.analysis.techStack).toEqual(techStack);
    expect(result.analysis.overview).toEqual(overview);
    expect(result.analysis.functions.map((item) => item.name)).toContain('hello');
    expect(result.aiReadme).toBe('# AI README\n\nGenerated by AI.');
    expect(openrouterMocks.callOpenRouterStructured).toHaveBeenCalledTimes(4);
    expect(firebaseMocks.setDoc).toHaveBeenLastCalledWith(
      'repos',
      'repo-1',
      expect.objectContaining({
        status: 'ready',
        aiReadme: '# AI README\n\nGenerated by AI.',
        aiReadmeStatus: 'ready',
        analysisModel: 'deepseek/test-model',
        analysisSourceHash: 'hash-1',
        analysisError: null,
      }),
      { merge: true }
    );
  });

  it('falls back locally and skips later AI steps after an AI provider failure', async () => {
    openrouterMocks.callOpenRouterStructured.mockRejectedValueOnce(new Error('rate limited'));

    const result = await extractAll('repo-1', 'demo-api', 'package.json\nsrc/index.ts\nREADME.md', files);

    expect(openrouterMocks.callOpenRouterStructured).toHaveBeenCalledTimes(1);
    expect(openrouterMocks.formatOpenRouterFailure).toHaveBeenCalledWith(expect.any(Error));
    expect(result.analysis.techStack).toMatchObject({ language: 'TypeScript', framework: 'Express' });
    expect(result.aiReadme).toContain('# Demo API');
    expect(firebaseMocks.setDoc).toHaveBeenLastCalledWith(
      'repos',
      'repo-1',
      expect.objectContaining({
        status: 'ready',
        aiReadmeStatus: 'ready',
        analysisError: null,
      }),
      { merge: true }
    );
  });
});
